### ISSUE TITLE
Fehler bei Auswertung FEMDuration mit vorangestellten "+"

### ISSUE THREAD

**Issue by PiQ99** [Sebastian-Rostock/java.bee-creative#1]
**Zusammenfassung**
Fehler bei Auswertung FEMDuration mit vorangestellten "+"

**Schritte zur Reproduktion**
Modul mit Zeitangabe "+" 
```<zeitspanne>+P1D</zeitspanne>```

**Bug**
```
Exception in thread "main" java.lang.IllegalArgumentException
	at bee.creative.fem.FEMDuration.from(FEMDuration.java:198)
```
bei Auswertung von Wert mit "+"

**Erwartetes Verhalten**
Korrekte Interpretation des Wertes

**Additional info**
In Klasse `bee.creative.fem.FEMDuration` und Methode `public static FEMDuration from(String string) throws NullPointerException, IllegalArgumentException` den Fall mit vorangestellten "+" auswerten
```java
		final boolean negate;
		if (symbol == '-') {
			symbol = buffer[1];
			negate = true;
			offset = 2;
		} else if (symbol == '+') {
			symbol = buffer[1];
			negate = false;
			offset = 2;
		} else {
			negate = false;
			offset = 1;
		}
```
Das getestete DL-KM liegt in der Version von 2016 vor.

**Comment by Sebastian-Rostock** [comment]
FEMDuration.from(String) verwendet das Format xsd:duration gemäß XML Schema Part 2: Datatypes Second Edition, beschränkt auf genau drei optionale Nachkommastellen für die Sekunden ( http://www.w3.org/TR/xmlschema-2/#duration-lexical-repr ).
Dort ist nur - als Vorzeichen spezifiziert. Das + wird daher als ungültig abgelehnt.
